### ISSUE TITLE
The last part's body contains closing boundary

### ISSUE THREAD

**Issue by revyh** [zefir-git/Multipart.ts#13]
Reproduction code
```js
import { Multipart } from "multipart-ts";

const input = `
Content-Type: multipart/mixed; boundary="boundary"

--boundary
Content-Type: text/plain

This is the first part of the message.

--boundary
Content-Type: text/html

<html>
<body>
<p>This is the second part of the message in HTML format.</p>
</body>
</html>

--boundary
Content-Type: application/json
Content-Disposition: attachment; filename="data.json"

{
"key": "value"
}

--boundary--`.replaceAll('\n', '\r\n');

const multipart = Multipart.parse(new TextEncoder().encode(input));
const bodies = multipart.parts.map(part => new TextDecoder().decode(part.body));

console.log(bodies);
```

It gives the following output:
```js
[
  "This is the first part of the message.\r\n",
  "<html>\r\n<body>\r\n<p>This is the second part of the message in HTML format.</p>\r\n</body>\r\n</html>\r\n",
  "{\r\n\"key\": \"value\"\r\n}\r\n\r\n--boundary--"
]
```

You can see that the last part's body ends with the `--boundary--` closing boundary, which should be stripped.

I added extra CRLFs just to make the example work. Usage of the `multipart-ts` on real data produces the same issue.

**Comment by zefir-git** [comment]
I think this might be due to lacking CRLF (\r\n) after the end boundary in your sting, which I believe is required, but I will have to double-check the RFC to be sure on that

**Comment by zefir-git** [comment]
I have confirmed that the issue is caused by the lack of CRLF after the closing boundary delimiter line.

RFC 2046 5.1.1.:
> The boundary delimiter line is then defined as a line
   consisting entirely of two hyphen characters ("-", decimal value 45)
   followed by the boundary parameter value from the Content-Type header
   field, optional linear whitespace, **and a terminating CRLF**.

> The boundary delimiter line following the last body part is a
   distinguished delimiter that indicates that no further body parts
   will follow.  Such a delimiter line is identical to the previous
   delimiter lines, with the addition of two more hyphens after the
   boundary parameter value.
   
Based on the above, I believe that a CRLF is required after every boundary (including the closing boundary).

<details>
<summary>I created a test Node HTTP server to test multipart/form-data generated by the browser which seems to work correctly.</summary>

The server in TypeScript (port 8080):

```ts
import http from "node:http";
import {Multipart} from "multipart-ts";

http.createServer(async (req, res) => {
    console.log(req.method, req.url, req.headers["content-type"]);
    if (req.method !== "POST" || !req.headers["content-type"]?.startsWith("multipart/")) {
        res.statusCode = 200;
        res.end("OK!");
        return;
    }

    const chunks: Uint8Array[] = []
    for await (const chunk of req) chunks.push(chunk);
    const body = Buffer.concat(chunks);

    const headers = Buffer.from("Content-Type: " + req.headers["content-type"] + "\r\n");

    try {
        const mp = Multipart.parse(Buffer.concat([headers, new Uint8Array([13, 10]), body]));
        console.log(mp);
        for (const part of mp.parts)
            console.log(Buffer.from(part.body).toString());

        res.statusCode = 200;
        res.end(body);
    }
    catch (e) {
        console.error(e);
        if (e instanceof SyntaxError) {
            res.statusCode = 400;
            res.end(e.stack);
            return;
        }
        res.statusCode = 500;
        res.end("Server error");
    }
}).listen(8080);
```

Browser JS code to send test FormData to `localhost:8080`:

```js
const send = async () => {
    const formData = new FormData();
    formData.append("username", "testuser");
    formData.append("email", "test@example.com");
    formData.append("file", new File([new Blob(["Hello world!"], {type: "text/plain"})], "sample.txt", {type: "text/plain"}));

    return await (await fetch("http://localhost:8080", {
        method: "POST",
        body: formData
    })).text();
}
await send();
```

</details>

**Comment by revyh** [comment]
Thanks! You're right. My backend sends ill-formed multipart data without closing CRLF.
